name = "HB Starter Theme Template"
license = "MIT"
licenselink = "https://github.com/jobcher"
description = "keep simple, keep stupid"
homepage = "https://github.com/jobcher"
demosite = "https://www.jobcher.com/"
tags = [
    "archive",
    "blog",
    "posts",
    "bootstrap",
    "dark",
    "dark mode",
    "docs",
    "gallery",
    "landing",
    "multilingual",
    "personal",
    "responsive"
]
features = ["search", "flexible", "modular"]
[author]
name = "jobcher"
homepage = "https://www.jobcher.com/"

# 网站地图配置
[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

[permalinks]
  posts = "/:slug/"

[outputs]
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]

# 数学公式
[params.math]
  enable = true